### ISSUE TITLE
Comments and suggestions about speed (purgeCSS & local assets)

### ISSUE THREAD

**Issue by tholop** [wangchucheng/hugo-eureka#141]
The Eureka theme looks great but feels quite slow. According to Google's benchmark:
![image](https://user-images.githubusercontent.com/32133147/138611552-d1b688c8-a2a4-477e-9f64-13bcb011424d.png)
It can take a few seconds to fully load the page, which is quite painful. The main reasons seem to be 1) render blocking resources and 2) unused CSS.

I think that there are a few low-hanging fruits that could improve significantly improve speed. For instance, look at the following coverage map:
![image](https://user-images.githubusercontent.com/32133147/138611539-73b37b85-773d-41df-8e57-fc157d39ae7a.png)

Here are a few ideas to improve things. I already tried some of them with encouraging results and I'm happy to open a PR (but I would need some help since I'm not a Hugo expert):
1. Eliminate unused CSS with a tool like PurgeCSS. `eureka.min.css` is truly enormous: 3.9M! I ran PurgeCSS by hand on my website and it reduced this file down to 12K. I'm not sure how to integrate it into the theme with Hugo pipes, but this resource might help: https://github.com/dirkolbrich/hugo-theme-tailwindcss-starter#how-does-that-work-anyway
2. Remove unused JS dependencies. It seems that HighlightsJS is always loaded even if we don't use syntax highlighting.
3. Give the option to serve JS libraries and fonts locally. For people who already serve their website over a CDN, it makes little sense to make another request to Google Fonts or JSDelivr.net (even if these websites are fast, the DNS+SSL handshake takes time and seems unnecessary). Here is an example where I tweaked Eureka to serve these assets locally: https://github.com/tholop/hugo-eureka. Also, it is better for privacy.
4. Only load the necessary icons from FontAwesome, instead of dumping a 1.2M .js file. I'm not sure if it's a good idea but we could look into the CSS version of FontAwesome, host it locally and prune it with PurgeCSS to only serve the icons that are actually used.

Thanks for reading and let me know what you think!

**Comment by cfu288** [comment]
Ran into a similar issue. For 1, I was able to get this working locally by copying the files from the 'assets/css' folder into my root folder then updating the `postcss.config.js` to the following:

```js
const themeDir = __dirname + '/../../'

module.exports = {
  plugins: [
    require('postcss-import')({
      path: [themeDir],
    }),
    require('tailwindcss')(themeDir + 'assets/css/tailwind.config.js'),
    require('autoprefixer')({
      path: [themeDir],
    }),
    require('@fullhuman/postcss-purgecss')({
      // see https://gohugo.io/hugo-pipes/postprocess/#css-purging-with-postcss
      content: ['./hugo_stats.json'],
      defaultExtractor: (content) => {
        let els = JSON.parse(content).htmlElements
        return els.tags.concat(els.classes, els.ids)
      },
    }),
  ],
}
``` 

and updating the config/_default/config.yaml with this:
```yaml
build:
  writeStats: true
```

`hugo --minify` now minifies my css file to 12KB vs 4MB.

**Comment by cfu288** [comment]
We can tree shake the FA icons by adding the following:

`assets/js/font-awesome-min.js`:
```js
import {
  faCoffee,
  faUser,
  faGlobe,
  faAdjust,
  faSun,
  faMoon,
  faBars,
  faUserCircle,
  faCaretRight,
  faThList,
  faFolder,
  faClock,
  faCalendar,
  faEdit,
  faRss,
  faEnvelope,
} from '@fortawesome/free-solid-svg-icons'
import {library, dom} from '@fortawesome/fontawesome-svg-core'
import {
  faGithub,
  faLinkedin,
  faTwitter,
} from '@fortawesome/free-brands-svg-icons'

library.add(
  faCoffee,
  faUser,
  faGlobe,
  faAdjust,
  faSun,
  faMoon,
  faBars,
  faUserCircle,
  faCaretRight,
  faThList,
  faFolder,
  faClock,
  faCalendar,
  faEdit,
  faGithub,
  faRss,
  faEnvelope,
  faTwitter,
  faLinkedin,
)
dom.i2svg()
```

Updating the head: `layouts/partials/head.html` to include our script instead of the FA cdn script:
```
{{ $js := resources.Get "js/font-awesome-min.js" | js.Build "fa.min.js"}}
<script defer type="text/javascript" src="{{ $js.RelPermalink }}"></script>
```

And adding some deps to `package.json` (there might be a few packages that can be removed):

```js
...
  "dependencies": {
    "@fortawesome/fontawesome-free": "^5.15.4",
    "@fortawesome/fontawesome-svg-core": "^1.2.36",
    "@fortawesome/free-brands-svg-icons": "^5.15.4",
    "@fortawesome/free-regular-svg-icons": "^5.15.4",
    "@fortawesome/free-solid-svg-icons": "^5.15.4"
  }
}
```

All these changes improve my lighthouse score:
Before:
<img width="1916" alt="Screen Shot 2021-11-09 at 4 27 33 PM" src="https://user-images.githubusercontent.com/2985976/141150371-aad4f84f-258e-4675-84ca-beded51b3001.png">
After:
<img width="1789" alt="Screen Shot 2021-11-10 at 11 06 47 AM" src="https://user-images.githubusercontent.com/2985976/141150311-fc4aa968-24aa-4f1f-a919-14e8eb51852a.png">

**Comment by wangchucheng** [comment]
Hi all,

> 1. Eliminate unused CSS with a tool like PurgeCSS. `eureka.min.css` is truly enormous: 3.9M!

Eureka is supposed to purge css by default, but I found that the resources had been changed by a previous PR which made the css so large. And I have fixed this in 4aaf514. Since this would greatly improve the performance, I also released a new patch version 0.8.4.

I agree with point 2 and 3. And I think @cfu288 's solution of point 4 is pretty decent. Since I am not very familiar with font awesome, I will dive into point 4 and see want we can do to improve it. Any PR is also welcome.

Thanks all for your advices and contributions to Eureka ;-)

**Comment by cfu288** [comment]
Hey thanks @wangchucheng for making such a great theme!

My comment above for #4 was just a quick fix I used locally to minimize the bundle for my site. The only problem with my approach is that I'm hard coding the icons users can import so I can tree shake, but theoretically users may want to import any icon like in the authors section:

'''
social:
  - icon: envelope
    iconPack: fas
    url: mailto:example@example.com
  - icon: twitter
    iconPack: fab
    url: https://example.com/
  - icon: github
    iconPack: fab
    url: https://example.com/
'''

I haven't figured out a way to make these imports dynamic while still supporting tree shaking yet which is why I haven't tried to make a PR (also I'm sort of new to Hugo)

**Comment by wangchucheng** [comment]
Yes, that is a issue so I have not changed this. For now, I do not have a concise way to import dynamically. So if anyone has ideas, please fell free to post it.

在 2021年11月10日，12:03，Chris Fu ***@***.***> 写道：

﻿

Hey thanks @wangchucheng<https://github.com/wangchucheng> for making such a great theme!

My comment above for #4<https://github.com/wangchucheng/hugo-eureka/issues/4> was just a quick fix I used locally to minimize the bundle for my site. The only problem with my approach is that I'm hard coding the icons users can import so I can tree shake, but theoretically users may want to import any icon like in the authors section:

'''
social:

  *   icon: envelope
iconPack: fas
url: ***@***.******@***.***>
  *   icon: twitter
iconPack: fab
url: https://example.com/
  *   icon: github
iconPack: fab
url: https://example.com/
'''

I haven't figured out a way to make these imports dynamic while still supporting tree shaking yet which is why I haven't tried to make a PR (also I'm sort of new to Hugo)

**Comment by wangchucheng** [comment]
An update on this: Eureka now reduce Font Awesome size with tree shaking in [89c48bd](https://github.com/wangchucheng/hugo-eureka/commit/89c48bd92b34b165770069b01aa9e2511d0448ca). Based on the icons we have used now, Font Awesome JS will be ~50kb instead of ~1.2mb.
