### ISSUE TITLE
Youtube Video

### ISSUE THREAD

**Issue by sugawara-system** [wangchucheng/hugo-eureka#15]
Would you please add a feature of inserting video like featuredImage?

Thank you very much.

**Comment by wangchucheng** [comment]
@sugawara-system I'll look at its feasibility. If possible, I will add this feature in the future. Because there are many video platforms, perhaps some of them have their own limitations.

And if you just want to add a video in content instead of summary, you can just insert the html code in markdown file.

**Comment by wangchucheng** [comment]
@sugawara-system This feature has been added in v0.3.0. You can upgrade to v0.3.0 and check [eureka‘s document](https://www.wangchucheng.com/en/docs/eureka/content-management/#post-page-front-matters) to use it.

**Comment by sugawara-system** [comment]
It worked perfectly. Great work! Thank you so, so much.
